name: Deploy to hostinger

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Haciendo deploy
    steps:
      - uses: actions/checkout@v1
      - name: Instalando php y composer
        uses: MilesChou/composer-action@master
        with:
          args: install --ignore-platform-reqs
      - name: Instalando node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run production
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      - run: 'echo "$ENV" > .env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}
      - run: sudo chmod 700 ./key
      - name: Deploy to hostinger
        run: rsync -hvrPt -e "ssh -i ./key -p ${{ secrets.REMOTE_PORT }} -oStrictHostKeyChecking=no" . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}