name: Deploy to hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Haciendo deploy
    steps:
      - uses: actions/checkout@v1
      - name: Instalando php y composer
        uses: MilesChou/composer-action@master
        with:
          args: install --ignore-platform-reqs --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - name: Instalando node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run production
      - run: rm -rf .git
      - run: rm -rf .github
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      - run: 'echo "$ENV" > .env'
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}
      - run: sudo chmod 700 ./key
      - name: Deploy to hostinger
        run: rsync -rav -e "ssh -i ./key -p ${{ secrets.REMOTE_PORT }} -oStrictHostKeyChecking=no" --progress --exclude={"node_modules","key"} . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}
      - name: 'Run migrations'
        run: ssh -i ./key -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "cd ${{ secrets.TARGET }}; php artisan migrate --force"
